# Generated by Django 4.2.18 on 2025-02-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttastModel',
            new_name='AttestModel',
        ),
    ]
